create or replace function public.has_legajo_admin_role()
returns boolean
language sql
stable
security definer
set search_path to 'public'
as $function$
  select exists (
    select 1
    from public.usuario_roles ur
    left join public.usuarios u on u.id = ur.usuario_id
    where (
        ur.usuario_id = (select auth.uid())
        or u.auth_user_id = (select auth.uid())
      )
      and ur.rol_id = 19
  );
$function$;

create table if not exists public.feriados (
  id bigint generated by default as identity primary key,
  fecha date not null unique,
  nombre text not null check (btrim(nombre) <> ''),
  observacion text,
  created_by uuid not null default auth.uid(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);

alter table public.feriados enable row level security;

drop policy if exists feriados_select_authenticated on public.feriados;
create policy feriados_select_authenticated
on public.feriados
for select
to authenticated
using (true);

drop policy if exists feriados_insert_legajo_admin on public.feriados;
create policy feriados_insert_legajo_admin
on public.feriados
for insert
to authenticated
with check (
  public.has_legajo_admin_role()
  and created_by = (select auth.uid())
);

drop policy if exists feriados_update_legajo_admin on public.feriados;
create policy feriados_update_legajo_admin
on public.feriados
for update
to authenticated
using (public.has_legajo_admin_role())
with check (public.has_legajo_admin_role());

drop policy if exists feriados_delete_legajo_admin on public.feriados;
create policy feriados_delete_legajo_admin
on public.feriados
for delete
to authenticated
using (public.has_legajo_admin_role());

create or replace function public.es_dia_laborable(p_fecha date)
returns boolean
language sql
stable
security definer
set search_path to 'public'
as $function$
  select extract(isodow from p_fecha) between 1 and 5
    and not exists (
      select 1
      from public.feriados f
      where f.fecha = p_fecha
    );
$function$;

revoke all on table public.feriados from public, anon;
grant select, insert, update, delete on table public.feriados to authenticated;
grant usage, select on sequence public.feriados_id_seq to authenticated;

revoke execute on function public.has_legajo_admin_role() from public, anon;
grant execute on function public.has_legajo_admin_role() to authenticated;

revoke execute on function public.es_dia_laborable(date) from public, anon;
grant execute on function public.es_dia_laborable(date) to authenticated;
